[package]
name = "ef_wasm_rust_01"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.8"
proxy-wasm = "0.1.0" # The Rust SDK for proxy-wasm

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]